### ISSUE TITLE
Unexpected Response

### ISSUE THREAD

**Issue by katymin** [PartTimeLegend/arewedrunkyet#3]
Application is returning an unexpected response. Are we drunk yet should equal Hell Yes

**Comment by WilfredKnievel** [comment]
Think we should get our heads together, this issue is going to require some serious strategising.

**Comment by katymin** [comment]
Agreed. something like this cannot go un-remedied

**Comment by PartTimeLegend** [comment]
I think we can implement a quick solution via [cocktail](https://github.com/CocktailJS/cocktail) and by using [Bar Mixvah](https://github.com/ytham/barmixvah).

**Comment by katymin** [comment]
Has anyone checked the bilge?

**Comment by PartTimeLegend** [comment]
There is a hole in my bilge atm.

**Comment by katymin** [comment]
get someone to pump it

**Comment by katymin** [comment]
update on this? we're dangerously close to breaking our SLA here.

**Comment by PartTimeLegend** [comment]
Closed with #4 .
